### ISSUE TITLE
CVE_2020_14825 java.util.PriorityQueue 无法反序列化

### ISSUE THREAD

**Issue by 0xlane** [rufherg/WebLogic_Basic_Poc#1]
使用的环境是14.1.1.0.0，测试过程中，weblogic日志如下：
```
 java.io.InvalidClassException: Expected type of [ , weblogic.rmi.spi.ServiceContext, weblogic.rjvm.ClassTableEntry, weblogic.rjvm.JVMID, weblogic.security.acl.internal.AuthenticatedUser, weblogic.rmi.extensions.server.RuntimeMethodDescriptor, weblogic.utils.io.Immutable] but actual type was java.util.PriorityQueue
java.io.InvalidClassException: Expected type of [ , weblogic.rmi.spi.ServiceContext, weblogic.rjvm.ClassTableEntry, weblogic.rjvm.JVMID, weblogic.security.acl.internal.AuthenticatedUser, weblogic.rmi.extensions.server.RuntimeMethodDescriptor, weblogic.utils.io.Immutable] but actual type was java.util.PriorityQueue
	at weblogic.utils.io.FilteringObjectInputStream.validateReturnType(FilteringObjectInputStream.java:156)
	at weblogic.utils.io.FilteringObjectInputStream.resolveClass(FilteringObjectInputStream.java:50)
	at weblogic.rjvm.InboundMsgAbbrev$ServerChannelInputStream.resolveClass(InboundMsgAbbrev.java:132)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1863)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1746)
	Truncated. see log file for complete stacktrace
```
显示PriorityQueue不在期盼的类中，请问有遇到这个问题吗

**Comment by rufherg** [comment]
这个问题我没有遇到过，感觉应该是你的weblogic环境或者配置的问题，你自己之前有成功打过CC链吗，PriorityQueue这个链
![image](https://user-images.githubusercontent.com/37505703/97429972-2180c800-1953-11eb-979f-af9e0c0bdd0a.png)
我打payload时的调用栈不是weblogic自己的ObjectInputStream。看样子你是自定义了Filter？我也不太能确定

**Comment by 0xlane** [comment]
我看你的堆栈也是经过了weblogic.rjvm.InboundMsgAbbrev.readObject这里，

我对比了一下12.2.1.3版本和14.1.1.0版本这里的区别：

旧版本调用的是readObject，而14的调用的readObjectValidated：
12.2.1.3:
![image](https://user-images.githubusercontent.com/22788893/97563048-80127880-1a1d-11eb-99d7-6be6cef44c2d.png)
14.1.1.0:
![image](https://user-images.githubusercontent.com/22788893/97563560-2fe7e600-1a1e-11eb-8752-fd86b3063825.png)

> wlthint3client.jar!/weblogic/rjvm/InboundMsgAbbrev.class

readObjectValidated限制了读取的object类型必须是ABBREV_CLASSES其中的一个：
![image](https://user-images.githubusercontent.com/22788893/97563750-76d5db80-1a1e-11eb-9971-75095701a517.png)

不知道你那边利用这套poc，在14版本利用的时候会不会碰到

**Comment by rufherg** [comment]
感谢你指出的问题，看来就是版本不同造成的调用差异。很抱歉，由于我测试环境是12.1.4.0，并没有测试14.1.1.10，因此poc的通用性可能会造成影响。这是我的疏忽，等这几天手头事情忙完，我将对几个版本进行测试及修改出不同版本的poc，谢谢指出问题~~~
